#!/bin/sh
set -ex
# docker hub username
USERNAME="$1"
VERSION="$2"
IMAGE="ffmpeg"
OS="alpine"
OS_SAFE=$(echo $OS | sed -e "s/\//-/g") # in case of base/image such as arm32v6/alpine
echo $OS
OS_VERSION="3.7"
LOCAL_DIR="${IMAGE}-${VERSION}-${OS_SAFE}"
README="${LOCAL_DIR}/README.md"
./gen-dockerfile.sh Dockerfile.alpine "$USERNAME" "$VERSION" "$OS:$OS_VERSION" >"$LOCAL_DIR/Dockerfile"
# mkdir "$LOCAL_DIR"
# cat Dockerfile.alpine | sed "s/{{from}}/$OS:$OS_VERSION/" | sed "s/{{image}}/$IMAGE/" | sed 's/{{user}}/sitkevij/' | sed 's/{{version}}/3.4.1/' | sed 's/{{description}}/Small ffmpeg Docker images for Alpine Linux, Ubuntu with VMAF option/'
# image="$IMAGE" user="$USERNAME" version="$VERSION" description="Small ffmpeg Docker images for Alpine Linux, Ubuntu with VMAF option" from="${OS}:${OS_VERSION}" mo Dockerfile.alpine >"$LOCAL_DIR/Dockerfile"
docker build --no-cache -t "$USERNAME/$IMAGE:latest" -t "$USERNAME/$IMAGE:$VERSION-$OS_SAFE" "$LOCAL_DIR"
echo "# ${IMAGE} ${VERSION} ${OS} ${OS_VERSION}" >"${README}"
echo "## Running" >>"${README}"
echo "\`\`\`" >>"${README}"
echo "docker run --rm sitkevij/${IMAGE}:${VERSION}-${OS_SAFE}" >>"${README}"
echo "\`\`\`" >>"${README}"
echo "## Pulling from Docker Hub" >>"${README}"
echo "\`\`\`" >>"${README}"
echo "docker pull sitkevij/${IMAGE}:${VERSION}-${OS_SAFE}" >>"${README}"
echo "\`\`\`" >>"${README}"
echo "## Building from source" >>"${README}"
echo "\`\`\`" >>"${README}"
echo "git clone https://github.com/sitkevij/ffmpeg.git && \\" >>"${README}"
echo "cd ffmpeg && \\" >>"${README}"
echo "chmod a+x build-local.sh && \\" >>"${README}"
echo "./build-local.sh sitkevij ${LOCAL_DIR} && \\" >>"${README}"
echo "docker run --rm sitkevij/${IMAGE}:${VERSION}-${OS_SAFE}" >>"${README}"
echo "\`\`\`" >>"${README}"
echo "## Buildconf" >>"${README}"
echo "\`\`\`" >>"${README}"
docker run --rm "$USERNAME/$IMAGE:$VERSION-$OS_SAFE" -version >>"${README}"
docker run --rm "$USERNAME/$IMAGE:$VERSION-$OS_SAFE" -buildconf >>"${README}"
echo "\`\`\`" >>"${README}"
echo "## Git repo" >>"${README}"
echo "https://github.com/${USERNAME}/${IMAGE}" >>"${README}"
echo "## Docker Hub repo" >>"${README}"
echo "https://hub.docker.com/r/${USERNAME}/${IMAGE}/" >>"${README}"
# see https://stackoverflow.com/questions/23137336/search-and-replace-with-bash
